// Player.js — the machine. State + arcade handling, plus a one-time
// procedurally drawn texture (no art assets needed yet).
//
// Handling model (deliberately fake, tuned for feel):
//   - position: distance along the track loop (world units)
//   - x: lateral position in road-halves: -1 = left edge, +1 = right edge
//   - steering authority scales with speed (can't turn a parked hovercar)
//   - curves apply an outward centrifugal push scaled by speed² — this is
//     the seed of the whole risk/reward design: speed through a curve is a
//     *decision*, not a free win.

export class Player {
  constructor(tuning) {
    this.t = tuning;
    this.position = 0;
    this.x = 0;
    this.speed = 0;
    this.steer = 0; // -1 | 0 | +1, for sprite lean
  }

  update(dt, input, model) {
    const t = this.t;
    const seg = model.findSegment(this.position + t.playerZ); // segment under the CAR, not the camera
    const speedPercent = this.speed / t.maxSpeed;

    // Steering. `2` = full road-widths per second at max speed.
    const dx = dt * 2 * speedPercent;
    if (input.left)       { this.x -= dx; this.steer = -1; }
    else if (input.right) { this.x += dx; this.steer =  1; }
    else                  { this.steer = 0; }

    // Centrifugal push: dx * speedPercent makes it scale with speed²,
    // so a curve that's trivial at half throttle is a fight at full.
    this.x -= dx * speedPercent * seg.curve * t.centrifugal;

    // Throttle / brake / coast.
    if (input.up)        this.speed += t.accel * dt;
    else if (input.down) this.speed += t.braking * dt;
    else                 this.speed += t.decel * dt;

    // Off the road (|x| > 1): heavy drag down to a crawl.
    if ((this.x < -1 || this.x > 1) && this.speed > t.offRoadLimit) {
      this.speed += t.offRoadDecel * dt;
    }

    this.x = clamp(this.x, -2, 2);
    this.speed = clamp(this.speed, 0, t.maxSpeed);

    // Advance along the loop.
    this.position += this.speed * dt;
    while (this.position >= model.trackLength) this.position -= model.trackLength;
    while (this.position < 0) this.position += model.trackLength;

    return seg; // handy for the scene (lean, later: scoring per-segment)
  }
}
// (The old procedural createTexture is gone — art now lives in
// public/assets/car.png, generated by tools/gen-car.js. This file is pure
// handling logic: no Phaser, no DOM, no pixels. Testable in plain Node.)

function clamp(v, lo, hi) {
  return Math.max(lo, Math.min(hi, v));
}